apiVersion: v2
name: verificator-svc
description: TokenD module creation pattern with pg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"
#kubeVersion: < 1.26.0-0
dependencies:
- name: postgresql
  version: 11.9.8
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
keywords:
- tokend
- miservice
- pg
home: https://tokend.io/
icon: https://tokend.io/images/logo.svg
sources:
  - https://gitlab.com/tokend/devops
  - https://gitlab.com/tokend/devops/service-template
maintainers:
  - name: Viktor Lysko
    email: vl@distributedlab.com
