{{- if .Values.NetworkPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}-{{- .Chart.Name }}-db-network-policy"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{- .Values.postgresql.nameOverride}}"
  policyTypes:
  - Egress
  - Ingress
  egress:
    - to:
      - podSelector:
            matchLabels:
              app.kubernetes.io/name: "{{- .Chart.Name }}"
      ports:
        - protocol: TCP
          port: 8000
  ingress:
    - from:
      - podSelector:
            matchLabels:
              app.kubernetes.io/name: "{{- .Chart.Name }}"
      ports:
        - protocol: TCP
          port: 5432
{{- end }}