{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-{{ include "template.fullname" . }}-data"
  annotations:
    reloader.stakater.com/auto: "true"
    pod-reloader.deckhouse.io/auto: "true"
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}